heat_template_version: 2015-04-30

description: affinity test

#parameters: 
#    service-flavour: 
#    type: string 
#    default: rhel6-cloud.1.2 
#    image: 
#    type: string 
#    default: redhat6 
#    key_name: 
#    type: string 
#    default: mykey 

resources: 
    y-key-pair:
        type: OS::Nova::KeyPair
        properties:
            name: y-key-pair
        #    type: ssh

    anti-svrgrp: 
        type: OS::Nova::ServerGroup 
        properties: 
            name: anti-svrgrp 
            policies: [ 'anti-affinity' ] 

    affinity-svrgrp: 
        type: OS::Nova::ServerGroup 
        properties: 
            name: affinity-svrgrp 
            policies: [ 'affinity' ] 

    aff-vm-1: 
        type: OS::Nova::Server 
        properties: 
            name: aff-vm-1
            flavor: yardstick-flavor
            image: yardstick-image 
            key_name: { get_resource: y-key-pair }
            scheduler_hints: 
                group: { get_resource: affinity-svrgrp} 

    aff-vm-2: 
        type: OS::Nova::Server 
        properties: 
            name: aff-vm-2
            flavor: yardstick-flavor
            image: yardstick-image 
            key_name: { get_resource: y-key-pair }
            scheduler_hints: 
                group: { get_resource: affinity-svrgrp }

    anti-vm-1: 
        type: OS::Nova::Server 
        properties: 
            name: anti-vm-1
            flavor: yardstick-flavor
            image: yardstick-image 
            key_name: { get_resource: y-key-pair }
            scheduler_hints: 
                group: { get_resource: anti-svrgrp }

    anti-vm-2: 
        type: OS::Nova::Server 
        properties: 
            name: anti-vm-2
            flavor: yardstick-flavor
            image: yardstick-image 
            key_name: { get_resource: y-key-pair }
            scheduler_hints: 
                group: { get_resource: anti-svrgrp }
